# Generated by Django 4.0.3 on 2022-06-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualspecies',
            name='env_variables',
        ),
    ]
