# Generated by Django 4.0.3 on 2022-06-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_remove_virtualspecies_env_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuploadfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='virtualspecies',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
