# Generated by Django 4.0.3 on 2022-06-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_myuploadfile_id_alter_virtualspecies_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='f_name',
        ),
        migrations.AddField(
            model_name='myuploadfile',
            name='mean',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='myuploadfile',
            name='std',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='myuploadfile',
            name='myfiles',
            field=models.FileField(upload_to='media/'),
        ),
    ]
