# Generated by Django 4.0.3 on 2022-06-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_remove_myuploadfile_f_name_myuploadfile_mean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuploadfile',
            name='mean',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='myuploadfile',
            name='std',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
