# Generated by Django 4.0.3 on 2022-06-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_alter_myuploadfile_mean_alter_myuploadfile_std_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='myuploadfile',
            name='std',
        ),
    ]
