# Generated by Django 4.0.3 on 2022-07-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_virtualspecies_env_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualspecies',
            name='env_variables',
        ),
        migrations.RemoveField(
            model_name='virtualspecies',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='virtualspecies',
            name='std',
        ),
    ]
