# Generated by Django 4.0.3 on 2022-07-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_virtualspecies_env_variables_virtualspecies_mean_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualspecies',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='virtualspecies',
            name='std',
        ),
    ]
